//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfServisCenter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextEF : DbContext
    {
        public ContextEF()
            : base("name=ContextEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Персонал> Персонал { get; set; }
        public virtual DbSet<Услуги> Услуги { get; set; }
        public virtual DbSet<ОказаниеУслуг> ОказаниеУслуг { get; set; }
        public virtual DbSet<СписокОказанияУслуг> СписокОказанияУслуг { get; set; }
        public virtual DbSet<Склад> Склад { get; set; }
        public virtual DbSet<СписокМатериаловСклада> СписокМатериаловСклада { get; set; }
    }
}
