//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfServisCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int Код { get; set; }
        public Nullable<int> КодКлиента { get; set; }
        public Nullable<int> КодМастера { get; set; }
        public Nullable<System.DateTime> ДатаПоступления { get; set; }
        public Nullable<System.DateTime> ДатаВыдачи { get; set; }
        public Nullable<int> Статус { get; set; }
        public Nullable<int> Цена { get; set; }
        public string Описание { get; set; }
        public string Техника { get; set; }
        public string Ответ { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Персонал Персонал { get; set; }
    }
}
