//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfServisCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class СписокОказанияУслуг
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public СписокОказанияУслуг()
        {
            this.ОказаниеУслуг = new HashSet<ОказаниеУслуг>();
        }
    
        public int Код { get; set; }
        public Nullable<int> КодКлиента { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Стоимость { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОказаниеУслуг> ОказаниеУслуг { get; set; }
    }
}
