//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfServisCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class СписокМатериаловСклада
    {
        public int Код { get; set; }
        public Nullable<int> КодЗаказа { get; set; }
        public Nullable<int> КодСклада { get; set; }
        public int Количество { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Склад Склад { get; set; }
    }
}
